pull_request_rules:
  - name: automatic Dependabot merge when CI passes
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=ci/circleci: build"
      - status-success=pyup.io/safety-ci
      - base=master
    actions:
      merge:
        method: merge
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
